// 메뉴 카테고리
export const MENU_CATEGORY = {
    NEW: "🩵New🩵",
    BEST: "🎉BEST",
    MADE: "MADE",
    SALE: "💕SALE💕",
    OUTTER: "OUTTER",
    ONEPIECE: "ONEPIECE",
    KNIT: "KNIT",
    TSHIRT: "T-SHIRT",
    SHIRT: "SHIRT",
    BLOUSE: "BLOUSE",
    SKIRT: "SKIRT",
    PANTS: "PANTS",
};

// 메뉴 별 카테고리
export const CATEGORY_OF_MENU = {
    CATEGORY_NEW: {
        OUTER: "아우터",
        ONPIECE: "원피스",
        BLOUSE: "블라우스",
        KNIT: "니트",
        T_SHIRT: "티셔츠",
        SKIRT: "스커트",
        PANTS: "팬츠",
        UNDERWEAR: "언더웨어",
        BAKANGS: "바캉스룩",
    },

    CATEGORY_BEST: {
        OUTER: "아우터",
        ONPIECE: "원피스",
        BLOUSE: "블라우스",
        KNIT: "니트",
        T_SHIRT: "티셔츠",
        SKIRT: "스커트",
        PANTS: "팬츠",
        UNDERWEAR: "언더웨어",
        VACATION: "바캉스룩",
    },
    CATEGORY_MADE: {
        ALLDAY: "올데이",
        THIRD_LONG: "3기장",
        AURA: "아우라",
        IGERGI: "이거지",
        WATCH: "손목시계",
        NECKLACE: "목걸이",
    },
    CATEGORY_SALE: {
        EIGHTY_PERCENT: "80% 할인",
        TIMESALE_FIFTY_PERCENT: "타임세일 50%",
        ONE_PLUS_ONE: "원쁠원",
        EVENT: "이벤트",
    },
    CATEGORY_OUTTER: {
        HANDMADE: "핸드메이드",
        PADDING: "패딩",
        COAT: "코트",
        JACKET: "자켓",
        CARDIGAN: "가디건",
        VEST: "조끼",
        LETHER: "가죽",
        JUMPER: "점퍼",
    },
    CATEGORY_ONEPIECE: {
        HANDMADE: "핸드메이드",
        BLOUSE: "블라우스",
        MINI: "미니",
        MEDIUM: "미디움",
        LONG: "롱",
        H_LINE: "H라인",
        A_LINE: "A라인",
        L_LINE: "L라인",
        MERMADE: "머메이드",
        TWO_PIECE: "투피스",
    },
    CATEGORY_KNIT: {
        HANDMADE: "핸드메이드",
        LONG_SLEEVES: "긴소매",
        HALF_SLEEVES: "반소매",
        SLEEVE_LESS: "민소매",
        KNIT_CARDIGAN: "니트 가디건",
    },
    CATEGORY_TSHIRT: {
        HANDMADE: "핸드메이드",
        LONG_SLEEVES: "긴소매",
        HALF_SLEEVES: "반소매",
        SLEEVE_LESS: "민소매",
    },
    CATEGORY_SHIRT: {
        HANDMADE: "핸드메이드",
        LONG_SLEEVES: "긴소매",
        HALF_SLEEVES: "반소매",
    },
    CATEGORY_BLOUSE: {
        HANDMADE: "핸드메이드",
        PLAIN: "무지",
        SLEEVE_LESS: "민소매",
        PATTERN: "패턴",
        RIBBON_AND_TIE: "리본/타이",
        OFFSHOULDER: "오프숄더",
        LACE: "레이스",
    },
    CATEGORY_PANTS: {
        AURA: "아우라",
        SHORTS: "반바지",
        DENIM: "데님",
        TRAINNING: "트레이닝",
    },
};

// 판매 옷 사진
